#!/usr/bin/env bash

sudo delayed chmod 777 "$HOME"/Dropbox/emacs/doom.d/*.org "$HOME"/Dropbox/emacs/doom.d/*.el
sudo delayed chown --recursive --changes "$USER" "$HOME"/.doom.d/*.el "$HOME"/.doom.d/config.org                   
