#!/bin/bash

commit="$*"

clear
echo ""
echo "#adding all files#"
echo ""
git add -A
echo ""
echo "#commiting and pushing"#
echo ""
echo "#commit message:" "$commit"
echo ""
git commit -am "$commit" && git push
echo ""